services:
  khumcloud-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event 
    ports:
      - "9003:9000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kathmandu
      - POSTGRES_HOST=khumcloud-postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - khumcloud-postgres
    networks:
      - khumcloud-network
  khumcloud-postgres:
    image: postgres:15-alpine
    container_name: khumcloud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Kathmandu
      PGTZ: Asia/Kathmandu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - khumcloud-network

volumes:
  postgres_data:
  uploads:

networks:
  khumcloud-network:
    driver: bridge
